CORES = fceumm gambatte gpsp pcsx_rearmed picodrive snes9x2005_plus
CORES += beetle-pce-fast beetle-vb fake-08 mednafen_supafaust mgba pokemini race fbneo mame2003-plus prboom puae
CORES += neocd bmp2png retroarch a5200 a7800

###############################

# optional core vars
# *_REPO=
# *_HASH=
# *_CORE=
# *_FLAGS=
# *_MAKEFILE=
# *_BUILD_PATH=

a2600_REPO = https://github.com/libretro/stella2014-libretro
a2600_CORE = stella2014_libretro.so

a5200_CORE = a5200_libretro.so

a7800_CORE = prosystem_libretro.so
a7800_REPO = https://github.com/libretro/prosystem-libretro

beetle-pce-fast_REPO = https://github.com/libretro/beetle-pce-fast-libretro
beetle-pce-fast_CORE = mednafen_pce_fast_libretro.so

beetle-vb_REPO = https://github.com/libretro/beetle-vb-libretro
beetle-vb_CORE = mednafen_vb_libretro.so

fake-08_REPO = https://github.com/jtothebell/fake-08
fake-08_CORE = fake08_libretro.so
fake-08_BUILD_PATH = fake-08/platform/libretro

fceumm_REPO = https://github.com/libretro/libretro-fceumm

gambatte_REPO = https://github.com/libretro/gambatte-libretro

mednafen_supafaust_REPO = https://github.com/libretro/supafaust


#pcsx_rearmed_REPO = https://github.com/KMFDManic/pcsx_rearmed
pcsx_rearmed_MAKEFILE = Makefile.libretro
#pcsx_rearmed_HASH = 1fec8a9

picodrive_REPO = https://github.com/irixxxx/picodrive
picodrive_MAKEFILE = Makefile.libretro
#picodrive_HASH = c5d8fe3

pokemini_REPO = https://github.com/libretro/PokeMini
pokemini_MAKEFILE = Makefile.libretro

snes9x2005_plus_REPO = https://github.com/libretro/snes9x2005
snes9x2005_plus_FLAGS = USE_BLARGG_APU=1

mame2003-plus_REPO = https://github.com/libretro/mame2003-plus-libretro
mame2003-plus_CORE = mame2003_plus_libretro.so

fbneo_REPO = https://github.com/libretro/fbneo
fbneo_CORE = fbneo_libretro.so
#same version as garlicos
fbneo_HASH = db9f7e9
fbneo_BUILD_PATH = fbneo/src/burner/libretro

prboom_REPO = https://github.com/libretro/libretro-prboom
prboom_CORE = prboom_libretro.so
prboom_HASH = 6be5a20

retroarch_REPO = https://github.com/libretro/RetroArch
retroarch_CORE = retroarch
#retroarch 1.14
#retroarch_HASH = ad89b0c
#retroarch 1.15
#retroarch_HASH = 6616b80
#retroarch 1.16
#retroarch_HASH = 6c2cc45
retroarch_MAKEFILE = Makefile.m21

puae_REPO = https://github.com/libretro/libretro-uae
#puae_BR = 2.6.1
puae_CORE = puae2021_libretro.so 
#puae_HASH = 6fd6bc9

neocd_REPO = https://github.com/libretro/neocd_libretro
neocd_CORE = neocd_libretro.so
neocd_HASH = 71ebe50

bmp2png_REPO = https://github.com/Turro75/bmp2png
bmp2png_CORE = bmp2png
###############################

include ../../all/cores/makefile
